name: Update QA Stand
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version}}

      - name: Install modules
        run: yarn install

      - name: Tests
        run: yarn test

      - name: Build
        run: yarn build

      - name: Deploy to s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{vars.FAUCET_UI_DEV_S3_BUCKET}}
          AWS_ACCESS_KEY_ID: ${{secrets.FAUCET_UI_DEV_AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.FAUCET_UI_DEV_AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: ${{secrets.AWS_REGION}}
          SOURCE_DIR: "build"
